### PR TITLE
feat: add i18n support for default error messages

### LINKED ISSUE #13: Support for i18n
Add the ability to provide translations, using gettext:
- Something went wrong
- We can't find the internet
- Info
- Error
- Attempting to reconnect
- Hang in there while we get back on track

I'll be glad to work on this if that's ok.

### PR DESCRIPTION
**Pull request by elephantoss**
@srcrip I test locally with a project of mine and it works as expected.

Please let me know if you don't like the direction of the solution and I can try to explore other ideas.

closes #13

### CODE REVIEW

**Comment by srcrip** [comment]
That is some really great looking work so far. I'm glad you opened this cause I don't use gettext much. Just assign me for review whenever you're ready for me to formally review. Only request I have is that it would be nice if we could have some tests around this.

**Comment by elephantoss** [comment]
@srcrip I'll add tests in the demo folder and I ping you when it is done

**Comment by elephantoss** [comment]
@srcrip I added the test but I don't have permission to assign you as a reviewer.

**Comment by srcrip** [comment]
Wonderful! I'll take a look.

**Comment by elephantoss** [comment]
@srcrip do you have any idea when you'll be able to review this PR?

**Comment by elephantoss** [comment]
@srcrip I think I've found a way to simplify this PR a little bit. I'll play around a bit and try to push a new version in the next couple of days

**Comment by elephantoss** [comment]
@srcrip just pushed a new version that is less intrusive and more straightforward to use.

**Comment by elephantoss** [comment]
@srcrip, I'd appreciate some feedback on this PR. Specially if there is anything preventing you from merging it.

Thanks in advance

**Review by srcrip — APPROVED** [review]

**Comment by srcrip** [comment]
Thank you! Sorry for the delay, I've been working on a different feature that's taken up a lot of my time for the project.

**Pull request merged**
